In [5]:
#Numpy
#Fast and efficient library for storing and manipulating data
#Numpy Arrays differ from python lists => faster,less space,more functionality,fixed size and type defined at creation

#Create a numpy array
import numpy as np
np_array = np.array([1,2,3,4,1])
print(np_array)

[1 2 3 4 1]


In [6]:
#unique : Gets the unique values
print(np.unique(np_array))

#std : Calculates the standard deviation
print(np.std(np_array))

#max : Calculates the maximun
print(np_array.max())

#squares of each value in the array
print(np_array ** 2)

#sum : Sum of squares the element
print(np.sum(np_array ** 2))

#Adds the arrays together element wise 
print(np_array + np_array)

#shape : Gives you the shape(number of rows , number of columns)
print(np_array.shape)

[1 2 3 4]
1.16619037896906
4
[ 1  4  9 16  1]
31
[2 4 6 8 2]
(5,)


In [7]:
#Two Dimensional Arrays : Represent matrix of data using numpy 

#Create a 2D array
import numpy as np
np_2D_array = np.array([[1,2,3],[4,5,6]])
print(np_2D_array)
print()

#Transpose : swap the columns and rows 
np_2D_array_T = np_2D_array.T
print(np_2D_array_T)
print()

#Shape 
print(np_2D_array_T.shape)
print()

#Accessing the elements of 2D array by index 
#1st index= row number , 2nd index = column number 
#Index starts from 0
print(np_2D_array[1,1])

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

(3, 2)

5


In [8]:
#Important Functionalities
#DOT Product : Calculating the dot product of 2 vectors

#dot
np_array_dot = np.array([1,2,3])
dot_product = np.dot(np_array_dot,np_array_dot)
print(dot_product)
print()

14



In [11]:
#Generating random Values
#rand() : Returns a random bumber or numbers between 0 and 1
#The number of random values returned depends on the shape provided to the function.If no shape given ,just a single number
#is returnd

#Generate a single random number in range [0,1]
print(np.random.rand())
print()

#Generate a list of 5 values
print(np.random.rand(5))
print()

#Generate a matrix of random number in range [0,1) with shape (3,2)
print(np.random.rand(3,2))
print()
      
#randint() : Returns random integers from low(inclusive) to high(exclusive) .low,high,size of the o/p
#Low=5,High=10,Size=2 : generate 2 values between 5 and 10(exclusive)
print(np.random.randint(5,10,2))
print()

#Low=5,High=10,Size=(3,2) : Generate a matrix of shape(3,2) with values between 5 and 10(exclusive)
print(np.random.randint(5,10,(3,2)))

0.556207452176991

[0.78913804 0.49463019 0.4693433  0.54146613 0.89778121]

[[0.81133911 0.77199427]
 [0.42892101 0.35935116]
 [0.06086093 0.81854796]]

[8 8]

[[9 5]
 [7 9]
 [5 9]]


In [12]:
#Sampling the data
#Sampling is the way to take smaller groups from a population
#choice() : allows you to pass an array,specify how many values to sample,and decide whether sampling to be done with or without
#replacement. Sampling without replacement means the same value cant be sampled more than once

array = np.array([1,2,3,4,5])

#Sample 10 data points with replacement
print(np.random.choice(array,10,replace=True))

#Sample 3 data points without replacement
print(np.random.choice(array,3,replace=False))

[4 2 3 5 1 2 5 3 1 2]
[2 4 1]


In [41]:
#Randomly Shuffling values
#shuffle : randomly shuffle your array

x = [1,2,3,4,5,6,7,8,9,10] #create a list of 5 elements
np.random.shuffle(x)
print(x)
print() 

#seed : If you want the random selections to be same every time 
#np.random.seed() : we have to supply the function with an integer to seed the randomness,so the result can be replicated
#as long as the same seed is used.
np.random.seed(42)
y = [1,2,3,4,5,6]
np.random.shuffle(y)
print(y)

[10, 8, 1, 4, 6, 9, 3, 2, 7, 5]

[1, 2, 6, 3, 5, 4]
